# How to use it?
# docker compose -f docker-compose-prod.yml up

# https://stackoverflow.com/questions/24718706/backup-restore-a-dockerized-postgresql-database
# Backup your databases
# docker exec -t your-db-container pg_dumpall -c -U postgres > dump_`date +%d-%m-%Y"_"%H_%M_%S`.sql

# Restore your databases
# cat your_dump.sql | docker exec -i your-db-container psql -U postgres

version: '3'
services:
  # You can rename this service special for docker-hub like: ydubovitsky/memorush
  memorush-spring:
    container_name: memorush-spring
    build:
      dockerfile: ./docker/production/Dockerfile
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres_container:5432/postgres
      POSTGRES_USERNAME: postgres
      PROFILE_ACTIVE: ${PROFILE_ACTIVE:-h2}
      ADMIN_NAME: ${ADMIN_NAME:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      ALLOWED_ORIGINS_ARRAY: ${ALLOWED_ORIGINS_ARRAY:-http://localhost:3000}
      POSTGRES_DDL_AUTO: ${POSTGRES_DDL_AUTO:-update}
    depends_on:
      - postgres
      - pgadmin
    networks:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    container_name: postgres_container
    image: postgres:alpine3.17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: